/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorJugador;
import controlador.VistaJugador;
import java.util.ArrayList;
import java.util.Observable;
import javax.swing.JOptionPane;

import modelo.Jugador;
import modelo.Pregunta;
import modelo.Sistema;
import modelo.Usuario;

/**
 *
 * @author alumnoFI
 */
public class JugadorDialog extends javax.swing.JDialog implements VistaJugador {

    /**
     * Creates new form AgendaDialog
     */
    private ControladorJugador controlador;
    private String nombreD = "";

    public JugadorDialog(java.awt.Frame parent, boolean modal, Usuario u) {
        super(parent, modal);
        initComponents();
        controlador = new ControladorJugador(u, this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLnombre = new javax.swing.JLabel();
        jTFacumulado = new javax.swing.JTextField();
        jLacumulado = new javax.swing.JLabel();
        jBjugar = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        jLbienvenida = new javax.swing.JLabel();
        jLbienvenida1 = new javax.swing.JLabel();
        jLacumulado1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLnombre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLnombre.setForeground(new java.awt.Color(0, 102, 0));
        jLnombre.setText("Nombre");
        getContentPane().add(jLnombre);
        jLnombre.setBounds(220, 160, 60, 30);

        jTFacumulado.setEditable(false);
        jTFacumulado.setBackground(new java.awt.Color(255, 255, 102));
        jTFacumulado.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTFacumulado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTFacumulado);
        jTFacumulado.setBounds(440, 20, 100, 30);

        jLacumulado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLacumulado.setText("$");
        getContentPane().add(jLacumulado);
        jLacumulado.setBounds(410, 20, 20, 30);

        jBjugar.setText("Jugar");
        jBjugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBjugarActionPerformed(evt);
            }
        });
        getContentPane().add(jBjugar);
        jBjugar.setBounds(260, 360, 110, 30);

        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBsalir);
        jBsalir.setBounds(403, 360, 120, 30);

        jLbienvenida.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLbienvenida.setText("!!! ");
        getContentPane().add(jLbienvenida);
        jLbienvenida.setBounds(290, 160, 100, 30);

        jLbienvenida1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLbienvenida1.setText("Bienvenid@");
        getContentPane().add(jLbienvenida1);
        jLbienvenida1.setBounds(110, 160, 100, 30);

        jLacumulado1.setText("Acumulado:");
        getContentPane().add(jLacumulado1);
        jLacumulado1.setBounds(330, 20, 70, 30);

        setBounds(0, 0, 574, 449);
    }// </editor-fold>//GEN-END:initComponents

    private void jBjugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBjugarActionPerformed
        // TODO add your handling code here:
        jugar();
    }//GEN-LAST:event_jBjugarActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBjugar;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLacumulado;
    private javax.swing.JLabel jLacumulado1;
    private javax.swing.JLabel jLbienvenida;
    private javax.swing.JLabel jLbienvenida1;
    private javax.swing.JLabel jLnombre;
    private javax.swing.JTextField jTFacumulado;
    // End of variables declaration//GEN-END:variables

    /* private void crearContacto() {
        controlador.jugar(jTFacumulado.getText(), jTFacumulado.getText());
    }*/
    private void jugar() {
        controlador.jugar();
    }

    private void limpiar() {
        jLnombre.setText("");
        jTFacumulado.setText("");
        // nombre.requestFocus();
    }

    private void salir() {
        dispose();
        new Login(null, false).setVisible(true);
    }

    @Override
    public void mostrarVistaJuego(Usuario u) {
        
        new pantallaJuego(null, false, u).setVisible(true);
    }

    @Override
    public void error(String msg) {
        JOptionPane.showMessageDialog(this, msg);

    }

    @Override
    public void mostrarCantidadAcumulado(int cantidad) {
        setTitle(nombreD + " - ");
        jTFacumulado.setText(Integer.toString(cantidad));
    }

    @Override
    public void mostrarNombreCompleto(String nombreCompleto) {
        nombreD = nombreCompleto.toUpperCase();
        setTitle(nombreD);
        jLnombre.setText(nombreD);
    }

}
