/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorLogin;
import controlador.VistaLogin;
import javax.swing.JOptionPane;
import modelo.Jugador;
import modelo.Sistema;
import modelo.Usuario;

/**
 *
 * @author alumnoFI
 */
public class Login extends javax.swing.JDialog implements VistaLogin{

    /**
     * Creates new form Login
     */
    private ControladorLogin controlador;
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controlador = new ControladorLogin(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 60, 30);
        getContentPane().add(nombre);
        nombre.setBounds(100, 30, 220, 30);
        getContentPane().add(password);
        password.setBounds(100, 80, 220, 30);

        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 70, 20);

        login.setText("Ingresar");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(193, 140, 130, 40);

        jLabel3.setText("Usuario: a - a / b - b");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 190, 120, 14);

        setBounds(0, 0, 388, 263);
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_loginActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login;
    private javax.swing.JTextField nombre;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables

    private void login() {
        String pwd = new String(password.getPassword());
        controlador.login(nombre.getText(), pwd);
    }
    @Override
    public void mostrarError(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }
    @Override
    public void mostrarVistaJugador(Usuario u) {
        dispose();
        new JugadorDialog(null,false,u).setVisible(true);
    }
}
